apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  creationTimestamp: null
  name: "2671059995731494830"
  namespace: default
spec:
  interval: 30s
  ref:
    branch: main
  url: https://github.com/chitti-intel/test-flux
status: {}
