apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  creationTimestamp: null
  name: kcust6107842650172127823
  namespace: default
spec:
  interval: 5m0s
  path: clusters/provider-flux+cluster2/context/6107842650172127823
  prune: true
  sourceRef:
    kind: GitRepository
    name: "6107842650172127823"
  targetNamespace: default
status: {}
