apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  creationTimestamp: null
  name: kcust223006456042169598
  namespace: default
spec:
  interval: 5m0s
  path: clusters/provider-flux+cluster2/context/223006456042169598
  prune: true
  sourceRef:
    kind: GitRepository
    name: "223006456042169598"
  targetNamespace: default
status: {}
