apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  creationTimestamp: null
  name: kcust2238769064784981779
  namespace: default
spec:
  interval: 5m0s
  path: clusters/provider-flux+cluster2/context/2238769064784981779
  prune: true
  sourceRef:
    kind: GitRepository
    name: "2238769064784981779"
  targetNamespace: default
status: {}
