apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  creationTimestamp: null
  name: kcust962367472889281341
  namespace: default
spec:
  interval: 5m0s
  path: clusters/provider-flux+cluster2/context/962367472889281341
  prune: true
  sourceRef:
    kind: GitRepository
    name: "962367472889281341"
  targetNamespace: default
status: {}
