apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  creationTimestamp: null
  name: kcust2671059995731494830
  namespace: default
spec:
  interval: 5m0s
  path: clusters/provider-flux+cluster2/context/2671059995731494830
  prune: true
  sourceRef:
    kind: GitRepository
    name: "2671059995731494830"
  targetNamespace: default
status: {}
