apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  creationTimestamp: null
  name: kcust1421970083070425729
  namespace: default
spec:
  interval: 5m0s
  path: clusters/provider-flux+cluster2/context/1421970083070425729
  prune: true
  sourceRef:
    kind: GitRepository
    name: "1421970083070425729"
  targetNamespace: default
status: {}
