apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  creationTimestamp: null
  name: kcust6211985233940023258
  namespace: default
spec:
  interval: 1m0s
  path: clusters/provider-flux+cluster2/context/6211985233940023258
  prune: true
  retryInterval: 5m0s
  sourceRef:
    kind: GitRepository
    name: "6211985233940023258"
  targetNamespace: default
  timeout: 45s
status: {}
