apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  creationTimestamp: null
  name: kcust5799730306231448415
  namespace: default
spec:
  interval: 5m0s
  path: clusters/provider-flux+cluster2/context/5799730306231448415
  prune: true
  sourceRef:
    kind: GitRepository
    name: "5799730306231448415"
  targetNamespace: default
status: {}
