apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  creationTimestamp: null
  name: kcust4500655848764694205
  namespace: default
spec:
  interval: 5m0s
  path: clusters/provider-flux+cluster2/context/4500655848764694205
  prune: true
  sourceRef:
    kind: GitRepository
    name: "4500655848764694205"
  targetNamespace: default
status: {}
