apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  creationTimestamp: null
  name: kcust948188762151608417
  namespace: default
spec:
  interval: 5m0s
  path: clusters/provider-flux+cluster2/context/948188762151608417
  prune: true
  sourceRef:
    kind: GitRepository
    name: "948188762151608417"
  targetNamespace: default
status: {}
