apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  creationTimestamp: null
  name: kcust8372820058601617630
  namespace: default
spec:
  interval: 5m0s
  path: clusters/provider-flux+cluster2/context/8372820058601617630
  prune: true
  sourceRef:
    kind: GitRepository
    name: "8372820058601617630"
  targetNamespace: default
status: {}
