apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  creationTimestamp: null
  name: kcust556271551721598494
  namespace: default
spec:
  interval: 1m0s
  path: clusters/provider-flux+cluster2/context/556271551721598494
  prune: true
  retryInterval: 5m0s
  sourceRef:
    kind: GitRepository
    name: "556271551721598494"
  targetNamespace: default
  timeout: 45s
status: {}
