apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  creationTimestamp: null
  name: kcust7851944854166532010
  namespace: default
spec:
  interval: 5m0s
  path: clusters/provider-flux+cluster2/context/7851944854166532010
  prune: true
  sourceRef:
    kind: GitRepository
    name: "7851944854166532010"
  targetNamespace: default
status: {}
