apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  creationTimestamp: null
  name: kcust9129211966085424999
  namespace: default
spec:
  interval: 5m0s
  path: clusters/provider-flux+cluster2/context/9129211966085424999
  prune: true
  sourceRef:
    kind: GitRepository
    name: "9129211966085424999"
  targetNamespace: default
status: {}
