apiVersion: k8splugin.io/v1alpha1
kind: ResourceBundleState
metadata:
  creationTimestamp: null
  labels:
    emco/deployment-id: 1601800953329408796-collectd
  name: 1601800953329408796-collectd
spec:
  selector:
    matchLabels:
      emco/deployment-id: 1601800953329408796-collectd
status:
  ready: false
  resourceCount: 0
